version: '3.9'
services:
  backend:
    image: car_rent_grpc
    build:
      dockerfile: dockerfile
    ports:
      - "5140:80"
    depends_on:
      - db
  
  db:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_USER=car_rent_user
      - POSTGRES_DB=car_rent_db
    volumes:
      - car_rent:/var/lib/postgresql/data
    ports:
      - 5432:5432

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
  
volumes:
  car_rent:

